### ISSUE TITLE
revision de fallos y tareas para implementar

### ISSUE THREAD

**Issue by JazminAime** [JazminAime/ahorrADAs#17]
Ya queda poco!!! 

- Lo que falta:
Seccion reportes: resumen, totales por categorìas, totales por mes.

- Para corregir:
Cuando editamos una categoria, se modifica en todos los select option, todo bien, peeeeero no se modifica en la operacion que ya esta cargada con esa categoria.

-Para implementar:
Ventanas para confirmar la eliminacion de una categoria o una operacion.

**Comment by Romiluu** [comment]
Jaz, solo faltan detalles!

- implemente las ventanas de cofirmacion al eliminar una operacion y al eliminar una categoria.
- Falta hacer que el reporte se oculte si no hay operaciones.

_Aun falta corregir:_
Cuando editamos una categoria, se modifica en todos los select option, todo bien, peeeeero no se modifica en la operacion que ya esta cargada con esa categoria.
y ademas tampoco se modifica en el reporte.
